### ISSUE TITLE
Is there the complete algorithm implementation of Neuro-DCF?

### ISSUE THREAD

**Issue by FlyerMaxwell** [mununum/ns3-gym-csmarl#1]
It seems that there is only the environment of Neuro-DCF. Is there the implementation of the proposed algorithm in Neuro-DCF?

**Comment by mununum** [comment]
Hi, you can check out "develop" branch rather than master. In experiments/ directory in develop branch, you can see our implementations of Neuro-DCF.

**Comment by FlyerMaxwell** [comment]
Thanks for your reply!

Could you further explain the environment requirement for this code? And which one is the main source file?

A brief starter may be helpful for other researchers to implyment your work.

**Comment by mununum** [comment]
You can refer to docker/Dockerfile_* files in develop branch, for environmental requirements.

The main source files are in experiments/ratecontrol/ directory.
Particularly, "experiments/ratecontrol/ns3_gnn_peraction.py" is the main Neuro-DCF training code,
and "experiments/ratecontrol/ns3_rollout.py" is the Neuro-DCF testing code.

You can use docker image for convenience.
Use docker/Dockerfile_src to build the docker image,
and docker/run.sh to make the docker container.
Use "docker/get_model.py" for extracting the trained model in the container,
"docker/put_model.py" for make a container with the trained model.

Sorry for messed up code, it contains a lot of side experiments while doing research :)

**Comment by FlyerMaxwell** [comment]
Thanks a million. I'll try and enjoy it.  :)

**Comment by FlyerMaxwell** [comment]
Hi, I have some trouble trying this project. I am not familiar with docker so I configure it with my own PC. I wonder wheather I  have configured the environment successfully. I turn to branch 'develop' and configure the environment step by step with your instruction. When I run './scratch/opengym/simple_test.py', I got the following response. Have I configure it successfuly?

![0971a6eeef12e25fb2a9b962b3b3653](https://user-images.githubusercontent.com/37821095/139805481-73251ac1-072e-4110-8694-2f8335650492.jpg)
